## 1. Variabel dan Fungsi

Penjelasan :
- Variabel: Simbol untuk menyimpan nilai yang bervariasi atau dapat berubah.
- Fungsi: Aturan yang mendefinisikan hubungan antara variabel input dan output, ditulis sebagai $y=f(x)$.
- Multivariable Function: Fungsi dengan lebih dari satu variabel input, contohnya $y=f(x_1, x_2, x_3)$.
- Composite Function (Fungsi Komposit): Fungsi yang bergantung pada fungsi lain.Contoh: Harga $h = f_1(k, d) = 10000 \times k - d$, di mana diskon $d = f_2(t) = 100 \times t$.

In [1]:
# Definisi fungsi komposit
def f2(t):
    """Menghitung nilai diskon berdasarkan tanggal"""
    return 100 * t

def f1(k, d):
    """Menghitung harga akhir berdasarkan kuantitas dan diskon"""
    return (10000 * k) - d

# Implementasi
k = 5  # kuantitas
t = 10 # tanggal

d = f2(t)
h = f1(k, d)

print(f"Nilai diskon (d) = {d}")
print(f"Harga pembelian (h) = {h}")

Nilai diskon (d) = 1000
Harga pembelian (h) = 49000


## 2. Struktur dan Operasi pada Data (Skalar, Vektor, dan Matriks)

Penjelasan: 
- Skalar: Nilai yang hanya memiliki besaran (contoh: suhu 37.5).
- Vektor: Serangkaian skalar yang memiliki urutan, besaran, dan arah. Bisa berupa vektor baris atau vektor kolom (menggunakan operasi Transpose $T$).
- Matriks: Susunan skalar dengan baris ($m$) dan kolom ($n$), berukuran $m \times n$. 
- Dataset tabular dalam ML umumnya disimpan sebagai matriks.Kita dapat melakukan operasi aljabar linier seperti perkalian dot product, penjumlahan, pengurangan, dan perkalian skalar.

In [2]:
import numpy as np

# Mendefinisikan Vektor dan Matriks
a = np.array([[1], [2]]) # Vektor kolom
B = np.array([[3, 5], [4, 6]]) # Matriks 2x2
C = np.array([[7, 9], [8, 10]]) # Matriks 2x2

print("Vektor a:\n", a)
print("\nTranspose Vektor a:\n", a.T)

# Operasi Matematika
print("\n1. Penjumlahan Matriks (B + C):\n", B + C)
print("\n2. Pengurangan Matriks (B - C):\n", B - C)
print("\n3. Perkalian Skalar (10 * B):\n", 10 * B)

# Dot Product (Perkalian Vektor baris dengan Matriks)
# Catatan: Syarat dot product, kolom matriks 1 = baris matriks 2
# Pada contoh teks, a transpos (baris) dikali B: [1, 2] * [[3,5], [4,6]]
dot_product = np.dot(a.T, B) 
print("\n4. Dot Product (a.T * B):\n", dot_product)

Vektor a:
 [[1]
 [2]]

Transpose Vektor a:
 [[1 2]]

1. Penjumlahan Matriks (B + C):
 [[10 14]
 [12 16]]

2. Pengurangan Matriks (B - C):
 [[-4 -4]
 [-4 -4]]

3. Perkalian Skalar (10 * B):
 [[30 50]
 [40 60]]

4. Dot Product (a.T * B):
 [[11 17]]


## 3. Tensor
Penjelasan:

Tensor adalah bentuk umum atau wadah penyimpanan angka dari berbagai dimensi yang menjadi struktur data utama dalam Deep Learning.

- 0D Tensor: Skalar (1 angka).
- 1D Tensor: Vektor (1 sumbu / serangkaian skalar).
- 2D Tensor: Matriks (2 sumbu / serangkaian vektor).
- 3D Tensor: Kubus angka (3 sumbu / serangkaian matriks).
- 4D & 5D Tensor: Wadah yang menyimpan kumpulan tensor dimensi sebelumnya secara bersarang.

In [ ]:
# Membuat berbagai dimensi Tensor menggunakan NumPy
tensor_0d = np.array(5)
tensor_1d = np.array([1, 2, 3])
tensor_2d = np.array([[1, 2], [3, 4]])
tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(f"Tensor 0D (Skalar): {tensor_0d.ndim} dimensi")
print(f"Tensor 1D (Vektor): {tensor_1d.ndim} dimensi, shape: {tensor_1d.shape}")
print(f"Tensor 2D (Matriks): {tensor_2d.ndim} dimensi, shape: {tensor_2d.shape}")
print(f"Tensor 3D: {tensor_3d.ndim} dimensi, shape: {tensor_3d.shape}")

Tensor 0D (Skalar): 0 dimensi
Tensor 1D (Vektor): 1 dimensi, shape: (3,)
Tensor 2D (Matriks): 2 dimensi, shape: (2, 2)
Tensor 3D: 3 dimensi, shape: (2, 2, 2)


## 4. Turunan (Derivative) dan Kemiringan Kurva

Penjelasan:

**Turunan:** Laju perubahan nilai output terhadap perubahan input yang sangat kecil.  
Secara geometris, ini adalah kemiringan (gradien) garis singgung (*Tangent Line*) pada satu titik di kurva.

**Chain Rule (Aturan Rantai):** Digunakan untuk mencari turunan fungsi komposit:

$$
\frac{dy}{dx} = \frac{dy}{du} \times \frac{du}{dx}
$$

**Turunan Parsial:** Mencari turunan fungsi multivariable secara terpisah, di mana saat satu variabel diturunkan, variabel lain dianggap konstanta:

$$
\partial
$$

In [5]:
import sympy as sp

# Mendefinisikan simbol
x, y = sp.symbols('x y')

# 1. Turunan fungsi tunggal: y = 0.5 * x^2
f_x = 0.5 * x**2
turunan_f = sp.diff(f_x, x)
print("Fungsi f(x):", f_x)
print("Turunan f'(x):", turunan_f)
print("Kemiringan di x = -2:", turunan_f.subs(x, -2)) # Substitusi x = -2

print("-" * 30)

# 2. Turunan Parsial (Multivariable): z = x^2 + y^3
z = x**2 + y**3
turunan_z_terhadap_x = sp.diff(z, x)
turunan_z_terhadap_y = sp.diff(z, y)
print("Fungsi z(x,y):", z)
print("Turunan parsial terhadap x (dz/dx):", turunan_z_terhadap_x)
print("Turunan parsial terhadap y (dz/dy):", turunan_z_terhadap_y)

Fungsi f(x): 0.5*x**2
Turunan f'(x): 1.0*x
Kemiringan di x = -2: -2.00000000000000
------------------------------
Fungsi z(x,y): x**2 + y**3
Turunan parsial terhadap x (dz/dx): 2*x
Turunan parsial terhadap y (dz/dy): 3*y**2


## 5. Pencarian Titik Terdalam (Dasar Gradient Descent)

Penjelasan:

- Gradien digunakan sebagai penunjuk arah untuk mencari nilai minimum suatu fungsi (titik terdalam kurva).

- Jika gradien negatif (kurva turun ke kanan), gerakkan variabel input $x$ ke arah positif (kanan).

- Jika gradien positif (kurva naik ke kanan), gerakkan variabel input $x$ ke arah negatif (kiri).

- Berhenti jika gradien mencapai 0 (titik minimum).

- Ini adalah konsep fundamental dari Gradient Descent.



In [6]:
# Simulasi sederhana Gradient Descent untuk fungsi y = x^2
# Turunannya adalah dy/dx = 2x

x_current = 4.0 # Titik awal tebakan acak
learning_rate = 0.1 # Seberapa besar langkah yang diambil
epochs = 15 # Jumlah iterasi pencarian

print(f"Nilai awal x = {x_current}")

for i in range(epochs):
    # Hitung gradien saat ini (2x)
    gradient = 2 * x_current 
    
    # Update nilai x berlawanan dengan arah gradien
    x_current = x_current - (learning_rate * gradient)
    
    print(f"Iterasi {i+1}: Gradien = {gradient:.4f}, Update x = {x_current:.4f}")

print(f"\nNilai minimum tercapai di sekitar x = {x_current:.4f}")

Nilai awal x = 4.0
Iterasi 1: Gradien = 8.0000, Update x = 3.2000
Iterasi 2: Gradien = 6.4000, Update x = 2.5600
Iterasi 3: Gradien = 5.1200, Update x = 2.0480
Iterasi 4: Gradien = 4.0960, Update x = 1.6384
Iterasi 5: Gradien = 3.2768, Update x = 1.3107
Iterasi 6: Gradien = 2.6214, Update x = 1.0486
Iterasi 7: Gradien = 2.0972, Update x = 0.8389
Iterasi 8: Gradien = 1.6777, Update x = 0.6711
Iterasi 9: Gradien = 1.3422, Update x = 0.5369
Iterasi 10: Gradien = 1.0737, Update x = 0.4295
Iterasi 11: Gradien = 0.8590, Update x = 0.3436
Iterasi 12: Gradien = 0.6872, Update x = 0.2749
Iterasi 13: Gradien = 0.5498, Update x = 0.2199
Iterasi 14: Gradien = 0.4398, Update x = 0.1759
Iterasi 15: Gradien = 0.3518, Update x = 0.1407

Nilai minimum tercapai di sekitar x = 0.1407
